variables:
    SolutionBaseName: 'Dfc.ProviderPortal.FatProcessor'
    BuildPlatform: 'any cpu'
    BuildConfiguration: 'release'

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    ref: refs/tags/v1.10.3
    endpoint: 'GitHub (ESFA)'

pool:
  name: NCS - CI and CD
  demands:
  - msbuild
  - visualstudio

stages:
- stage: Build
  displayName: Build, Test and Analyze
  jobs:
  - job: BuildTestAndAnalyze
    steps:
    - template: AzureDevOpsTemplates\Build\StepTemplates\dfc-arm-build.yml@dfc-devops
      parameters:
        ArmTemplateRoot: '$(System.DefaultWorkingDirectory)\Resources\ArmTemplates'
        SolutionBaseName: '${{ variables. SolutionBaseName }}'
        PublishPipelineArtifact: true

    - template: AzureDevOpsTemplates\Build\StepTemplates\dfc-dotnetcore-build.yml@dfc-devops
      parameters:
        SolutionBaseName: '${{ variables.SolutionBaseName }}.PublicApi'
        BuildPlatform: '${{ variables.BuildPlatform }}'
        BuildConfiguration: '${{ variables.BuildConfiguration }}'
        DotNetCoreVersion: '3.1.101'
        PublishWebApp: true
        TestSuffix: UnitTests

    - template: AzureDevOpsTemplates\Build\StepTemplates\dfc-dotnetcore-build-notests.yml@dfc-devops
      parameters:
        SolutionBaseName: '${{ variables.SolutionBaseName }}.Functions'
        BuildPlatform: '${{ variables.BuildPlatform }}'
        BuildConfiguration: '${{ variables.BuildConfiguration }}'
        DotNetCoreVersion: '3.1.101'
        PublishWebApp: true
