variables:
    SolutionBaseName: 'Dfc.ProviderPortal.FatProcessor.PublicApi'
    BuildPlatform: 'any cpu'
    BuildConfiguration: 'release'

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    ref: refs/tags/v1.10.3
    endpoint: 'GitHub (ESFA)'

stages:
- stage: Build
  displayName: Build, Test and Analyze
  jobs:
  - job: BuildTestAndAnalyze
    pool:
      name: NCS - CI and CD
      demands:
      - msbuild
      - visualstudio
    steps:
    - template: AzureDevOpsTemplates\Build\StepTemplates\dfc-dotnetcore-build.yml@dfc-devops
      parameters:
        SolutionBaseName: 'Dfc.ProviderPortal.FatProcessor.PublicApi'
        BuildPlatform: 'any cpu'
        BuildConfiguration: 'release'
        DotNetCoreVersion: '3.1.101'
        PublishWebApp: true
        TestSuffix: UnitTests

    - template: AzureDevOpsTemplates\Build\StepTemplates\dfc-dotnetcore-build-notests.yml@dfc-devops
      parameters:
        SolutionBaseName: 'Dfc.ProviderPortal.FatProcessor.Functions'
        BuildPlatform: 'any cpu'
        BuildConfiguration: 'release'
        DotNetCoreVersion: '3.1.101'
        PublishWebApp: true
